config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'

  get '/about', to: 'pages#about'
  get '/resume', to: 'pages#resume'

  namespace :api do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    skip_before_action :verify_authenticity_token
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApiController

  def index
    render json: Post.all
  end

  def show
    post = Post.find(params[:id])
    render json: post
  end

  def create
    post = Post.new(post_params) 
    if post.save
      render status:200, json: {
        message: "You did it! Post successfully created.",
        post: post
      }.to_json
    else
      render status: 422, json: {
        message: "Hmm, that didn't work.  Try again.",
        errors: post.errors
      }.to_json
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    render status: 200, json: {
      message: "That post has been successfully deleted."
    }.to_json
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      render status: 200, json: {
        message: "Post successfully updated.",
        post: post
      }.to_json
    else
      render status: 422, json: {
        message: "The post could not be updated.",
        post: post
      }.to_json
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about; end
  def login; end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Recommended in the devise documentation
  protect_from_forgery prepend: true
  before_action :authenticate_user!, except: %i[index show]
  def index
    # @posts = Post.all.order('created_at DESC')
    @posts = Post.paginate :page => params[:page], :per_page => 10

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class='comment clearfix'>
  <div class='comment_content'>
    <p class='comment_name'><strong><%= comment.name %></strong></p>
    <p class='comment_body'><%= comment.body %></p>
    <p class='comment_time'><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>

  <% if user_signed_in? %>
    <p><%= link_to 'Delete', [comment.post, comment],
                    method: :delete,
                    class: 'button',
                    data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
  </p>

  <p>
  <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Inconsolata:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <div id='topnav'>
      <ul>
        <li class='category'>Here</li>
        <%# <li class='home_page_icon'><%= link_to((image_tag('project-2x.png', alt: 'blog home page icon')), root_path)></li> %>
        <%# </li> %>
        <li><%= link_to 'Blog', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Resumé', resume_path %></li>
        <li class='category'>Elsewhere</li>
        <li><a href='https://twitter.com/twoesplease' target ='_blank'>Twitter</a></li>
        <li><a href='https://github.com/twoesplease' target ='_blank'>Github</a></li>
        <li><a href='mailto:itisi@toneeyoung.com'>Email</a></li>
        <li style='float:right'><%=link_to 'Admin Login', login_path %></li>
      </ul>

      </div>

      <div id='main_content'>
        <div id='header'>
          <% if current_page?(root_path) %>
            <p>All Posts</p>
          <% elsif current_page?(about_path) %>
            <p>About</p>
          <% else %>
            <%= link_to 'Back to Home Page', root_path %>
          <% end %> 

        <% if user_signed_in? %>
          <%# Changing these to p tags instead of buttons breaks the styling but fixes the functionality. %>
          <p class='buttons'>
            <p class='button'><%= link_to 'New Post', new_post_path %></p>
            <p class='button'>Log Out</p>
         </p>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: 'alert') %>
      <% end %>

    <%= yield %>
      </div>

  </body>
</html>

app/views/pages/about.html.erb
<div id='page_wrapper'>
  <div>
    <%= image_tag 'profile.jpg', id: 'profile_image' %> 
  </div>

  <div id='content'>
     <h1>Tonee Young</h1><br>
     <h3>That's me.</h3>
     <p>I'm a non-binary queer human living in Atlanta. I spend my time on my dogs, transforming my urban home into a farmlet, <br>and learning to code.  Right now, I'm focusing on Ruby & Rails.</p>
      <p>I support <a href="http://sopobikes.org" target="_blank">SoPo Bicycle Cooperative</a> and <a href="http://southernersonnewground.org/" target="_blank">SONG (Southerners On New Ground)</a>, and it'd be great if you would too.</p>
      <p>You can follow me on twitter <a href="https://twitter.com/twoesplease" target="_blank">@twoesplease</a> & can check out my <a href="https://github.com/twoesplease" target="_blank">Github profile here</a>. 
      I'm working on a #144HoursOfCode challenge (based on the <a href="https://github.com/Kallaway/100-days-of-code" target="_blank"> 100 Days of Code Challenge</a>), 
      & I log my progress on that here on my blog at toneeyoung.com.</p>  I also completed a round of the #100DaysOfCode challenge, & I entered my progress during that challenge 
      <a href="https://github.com/twoesplease/100-days-of-code/blob/master/log_round_1.md" target="_blank">here</a>.

  </div>
</div>

app/views/pages/resume.html.erb
<div id='page_wrapper'>
  <div>
    <%= image_tag("ToneeYoungResume2018.jpg", height: '988.8', width: '765') %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id='errors'>
      <h2><%= pluralize(@post.errors.count, 'error') %> prevented this post from saving.</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>

  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
  <% end %>

app/views/posts/edit.html.erb
<div id='page_wrapper'>
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class='post_wrapper'>
    <h2 class='title'><%= link_to post.title, post %></h2>
    <p class='date'><%= post.created_at.strftime('%B %d, %Y') %></p>
  </div>
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div id='post_wrapper'>
<h1>New Post</h1>

<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div id='post_content'>
<h1 class='title'>
  <%= @post.title %>
</h1>

<p class='date'>
  Submitted <%= time_ago_in_words(@post.created_at) %> ago
  <% if user_signed_in? %>
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

<p class='body'>
  <%= markdown(@post.body) %>
</p>

<div id='comments'>
  <h2><%= @post.comments.count %> Comments</h2>
  <%= render @post.comments %>

  <h3>Add a comment:</h3>
  <%= render 'comments/form' %>
</div>
</div>